name: causal_inf_mixtape
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - statsmodels
  - jupyterlab
  - notebook
  - conda-forge::r-essentials
  - conda-forge::r-estimatr
  - conda-forge::r-plm
  - pip:
    - plotnine
